# Generated by Django 4.2.7 on 2023-11-17 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChopinEcstasy', '0003_alter_userprofile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='full_name',
        ),
    ]
